### ISSUE TITLE
workshops approved button

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices#76] opened 2016-12-08 17:23 UTC
Hi Andrew, 

can you look at the workshops approved button.

When we click on it it does not approve the workshop.

**Comment by Hoverbear** [comment] 2016-12-08 18:12
Confirmed, looks like something got misaligned on the table.

**Comment by Hoverbear** [comment] 2016-12-08 18:18
Fixed in https://github.com/BCAAFC/Gathering-Our-Voices/commit/42155bf55f602e9415484beffa8f655ab1018417, looks like I can't count. :)

**Closed as completed** 2016-12-08 18:18 UTC
